version: '2'
services:
  staticman:
    build: .
    env_file: .env
    ports:
      - '8080:3000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      GITHUB_TOKEN: #insert your GitHub token here
      RSA_PRIVATE_KEY: |
#        RSA private key to encrypt sensitive configuration parameters with.
#        the correct format starts with "-----BEGIN RSA PRIVATE KEY-----"